dalyac_test: dalyac_test.cpp
	g++ -Wall -g dalyac_test.cpp `pkg-config opencv --cflags --libs` -o dalyac_test

dalyac_test_readlink: dalyac_test_readlink.cpp
	g++ -Wall -g dalyac_test_readlink.cpp `pkg-config opencv --cflags --libs` -o dalyac_test_readlink
