## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda

# CUDA architecture setting: going with all of them (up to CUDA 5.5 compatible).
# For the latest architecture, you need to install CUDA >= 6.0 and uncomment
# the *_50 lines below.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35
		#-gencode=arch=compute_50,code=sm_50 \
		#-gencode=arch=compute_50,code=compute_50

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
BLAS := atlas
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
# (dalyac): output of 
# for dir in /usr/local ~ /data/ad6813/caffe/python/venv; do find $dir -name "Python.h" >> where_pythonh_arrayobject.out; find $dir -name "arrayobject.h" >> where_pythonh_arrayobject.out; done
# find /usr/local -name "Python.h"
# find /usr/local -name "arrayobject.h"
# find ~ -name "Python.h"
# find ~ -name "arrayobject.h"
# find /data/ad6813/caffe/python/venv -name "Python.h"
# find /data/ad6813/caffe/python/venv -name "arrayobject.h"
# are all in /data/ad6813/caffe/python/where_pythonh_arrayobject.out
PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/include/python2.7/numpy
# Anaconda Python distribution is quite popular. Include path:
# PYTHON_INCLUDE := $(HOME)/anaconda/include \
		# $(HOME)/anaconda/include/python2.7 \
		# $(HOME)/anaconda/lib/python2.7/site-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
PYTHON_LIB := /usr/lib/x86_64-linux-gnu/ \
	   /homes/ad6813/CUDA_SDK/gpu_sdk/CUDALibraries/common/FreeImage/lib/darwin
# PYTHON_LIB := $(HOME)/anaconda/lib

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /homes/ad6813/.local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib /homes/ad6813/.local/lib

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging.
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0
